### PR TITLE
Eric/api 21 section alternate names are missing the letter

### PR DESCRIPTION
**Pull request by econnally**
* see deltas [here](https://github.com/illustrativemathematics/static-ocx/pull/21/commits/9c97e12a7e68fee406b9204e7d0882e7459e7f66)
* relates to [this cms PR](https://github.com/illustrativemathematics/cms_im/pull/1160)
* see [story](https://linear.app/illustrativemathematics/issue/API-21/section-alternate-names-are-missing-the-letter)

### CODE REVIEW

**Comment by econnally** [comment]
@karln i noticed in places (e.g. lesson nodes like [this one](https://github.com/illustrativemathematics/static-ocx/pull/21/commits/9c97e12a7e68fee406b9204e7d0882e7459e7f66)) we are referring to the parent address as the `courseCode`. 
* should i always be using the course address here, not the parent address here? i.e. is this a bug?

**Comment by karln** [comment]
> @karln i noticed in places (e.g. lesson nodes like [this one](https://github.com/illustrativemathematics/static-ocx/pull/21/commits/9c97e12a7e68fee406b9204e7d0882e7459e7f66)) we are referring to the parent address as the `courseCode`.
> 
> * should i always be using the course address here, not the parent address here? i.e. is this a bug?

That's a bug, @econnally. It should be the *course*, not the parent, in the courseCode field.

**Comment by econnally** [comment]
> > @karln i noticed in places (e.g. lesson nodes like [this one](https://github.com/illustrativemathematics/static-ocx/pull/21/commits/9c97e12a7e68fee406b9204e7d0882e7459e7f66)) we are referring to the parent address as the `courseCode`.
> > 
> > * should i always be using the course address here, not the parent address here? i.e. is this a bug?
> 
> That's a bug, @econnally. It should be the _course_, not the parent, in the courseCode field.

alright @karln i'll open a separate story to keep these disentangled

**Comment by econnally** [comment]
@karln see [this new story](https://linear.app/illustrativemathematics/issue/API-61/fix-ispartof-coursecode-field) 
> > That's a bug, @econnally. It should be the _course_, not the parent, in the courseCode field.
> 
> alright @karln i'll open a separate story to keep these disentangled

**Pull request merged**
