### PR TITLE
Eric/api 70 leave the encoding property empty if there are no associated

### PR DESCRIPTION
**Pull request by econnally**
see:
* https://github.com/illustrativemathematics/cms_im/pull/1227
* https://linear.app/illustrativemathematics/issue/API-70/leave-the-encoding-property-empty-if-there-are-no-associated-files

### CODE REVIEW

**Comment by econnally** [comment]
@dylandechant @karln 
* delta a little noisy owing (i assume) to content changes in records themselves. 
* it's been awhile since i updated my local db (which is what i used to generate the build); i should do that more often

**Review by dylandechant — APPROVED** [review]
really interesting seeing the content changes from the content team on these...

**Comment by karln** [comment]
Pretty sure we're exporting the v3 tree (so, the maintained one, not the new one), so there shouldn't be many/any content changes.

**Comment by econnally** [comment]
> Pretty sure we're exporting the v3 tree (so, the maintained one, not the new one), so there shouldn't be many/any content changes.

@karln 
* i'm seeing content changes [like these](https://github.com/illustrativemathematics/static-ocx/pull/25/commits/e3fcfc8bc542a75a283d620c5283c3930bda338d#diff-26e953d1ed94c28ba6b1f615375e40180aba1267eb2baa3f0b5e3b5d4797dc44L75-R76)
* the last time i updated my local db before today is 2023-07-17, according to the most recent curl i have. possibly there have been content changes since then?
* it hadn't occurred to me that these static builds were based on moving content --- if as you say things are now frozen that shouldn't matter so much going forward
* LMK if anything seems amiss

**Comment by karln** [comment]
tbh, I'm surprised to see any content changes here. I can only assume that someone made them by mistake.

**Comment by econnally** [comment]
> tbh, I'm surprised to see any content changes here. I can only assume that someone made them by mistake.

@karln should we follow-up with writing team? i don't think it's anything in the code

**Comment by karln** [comment]
naw. Upon closer look, it looks like it was a learning target (tag) that was updated. Probably a tag shared across trees.

**Pull request merged**
