### PR TITLE
Chore/sc 8578/regenerate ocx for ms pi tree 215 grade 6

### PR DESCRIPTION
**Pull request by econnally**

### CODE REVIEW

**Comment by dylandechant** [comment]
@econnally i think this PR resolves the end part of this conversation, correct? [CONVERSATION](https://illustrativemath.slack.com/archives/C0441C2CKT9/p1686844652101669)

**Comment by econnally** [comment]
@dylandechant perhaps that is true, but this PR doesn't fix the underlyign problems in the api responses (bad URLs etc)

**Comment by econnally** [comment]
@karln @dylandechant can y'all look at this?

on a separate branch, i took the original files and renamed them. this PR is based against that branch (not master). this way, the before/after deltas should be easier to track

**Comment by econnally** [comment]
@dylandechant @karln

**Comment by econnally** [comment]
> The changes look reasonable, but I'm curious why the IDs changed for each file? I'd have thought those would persist.

i was wondering the same thing @karln 🤷🏻 i haven't figured it out yet

**Comment by econnally** [comment]
exported using this command:
```
reload!; Tree.find(215).ed_node.sad.where(ref_type: 'Unit').second.ocx_exporter.write
```

**Comment by econnally** [comment]
@dylandechant @karln 

FYI i haven't been able to tag maria on this story but she should look 

* i have added `hasParts` in a CMS PR: https://github.com/illustrativemathematics/cms_im/pull/1067
* there are 3 commits in this PR.
  1. in this commit i renamed files from the original build to make apples-to-apples comparisons easier
  2. in this commit i applied the work done to unwind the proxy object design. the ids changed for reasons i haven't yet figured out. it should however have fixed the math encoding & asset URLs
  3. in the 3rd commit i applied the new `hasParts` stuff.

note i also added a

**Review by dylandechant — APPROVED** [review]

**Pull request merged**
